### ISSUE TITLE
Got "Cannot fetch the page from Google Scholar" issue after fix citation_links 

### ISSUE THREAD

**Issue by zhjwy9343** [scholarly-python-package/scholarly#154] opened 2020-06-30 05:28 UTC
Dear,

I try to use publication.citedby. First I got the publication has no citation_links error. Thanks for another issue, I replace the publication.py 'total citation' lines.

Now I got the "Cannot fetch the page from Google Scholar" exception. I have test this in both US and China. Same results.

My codes:

from scholarly import scholarly

### Retrieve the author's data, fill-in, and print
search_query = scholarly.search_author('Matthias Fey')
author = next(search_query).fill()
print(author)

### Print the titles of the author's publications
print([pub.bib['title'] for pub in author.publications])

### Take a closer look at the first publication
pub = author.publications[0].fill()
print('The most popular paper.')
print(pub)

### Which papers cited that publication?
print([citation.bib['title'] for citation in pub.citedby()])

**Comment by chuntul** [comment] 2020-07-08 22:48
I get the same for every function call I've tried. On another computer, I have scholarly downloaded and I'm assuming it's an older version, because I am still using search_pubs_query, which is deprecated in favour of search_pubs in the updated docs, and my queries work. However, on the computer where I have the newer version of scholarly downloaded, it returns "Cannot fetch the page from Google Scholar." The basic usage case also returns this.

**Comment by Nicholas-Lewis-USDA** [comment] 2020-07-09 13:46
This is a duplicate, I will see after my meeting if I can't find you the proper thread for this.  It is a known bug that citedby isn't working.

**Comment by Nicholas-Lewis-USDA** [comment] 2020-07-09 16:03
Please refer to #141 
#150 I provided a possible work around but it was just me looking to see if  I could get any data to respond.

**Comment by chuntul** [comment] 2020-07-09 16:51
@Nicholas-Lewis-USDA Unfortunately, I don't think it's the citedBy function that's causing the problem here. I think the general search functions (search_author, search_pubs are the ones I've tried) just aren't working and will always output `Exception: Cannot fetch the page from Google Scholar`.

Code to reproduce, which is straight from the basic usage case provided in the README: 
```
from scholarly import scholarly
print(next(scholarly.search_author('Steven A. Cholewiak')))
```
This produces the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scholarly/_navigator.py", line 303, in search_authors
    soup = self._get_soup(url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scholarly/_navigator.py", line 292, in _get_soup
    html = self._get_page(_HOST.format(url))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scholarly/_navigator.py", line 129, in _get_page
    raise Exception("Cannot fetch the page from Google Scholar.")
Exception: Cannot fetch the page from Google Scholar.
```
Search_pubs gives me the same thing:
```
>>> scholarly.search_pubs('ice cream')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scholarly/_scholarly.py", line 152, in search_pubs
    return self.__nav.search_publications(url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scholarly/_navigator.py", line 347, in search_publications
    return _SearchScholarIterator(self, url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scholarly/publication.py", line 24, in __init__
    self._load_url(url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scholarly/publication.py", line 28, in _load_url
    self._soup = self._nav._get_soup(url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scholarly/_navigator.py", line 292, in _get_soup
    html = self._get_page(_HOST.format(url))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scholarly/_navigator.py", line 129, in _get_page
    raise Exception("Cannot fetch the page from Google Scholar.")
Exception: Cannot fetch the page from Google Scholar.
```

Weirdly enough, it was working a month ago, when I had the scholarly version 0.2.5, so I tried installing version 0.2.5. `print(next(scholarly.search_author('Steven A. Cholewiak')))` actually works, which is great! However, `search_pubs_query` (the old version of search_pubs), doesn't work anymore even though _it was working last month_. 

```
>>> print(next(scholarly.search_pubs_query('Perception of physical stability and center of mass of 3D objects')))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
StopIteration
```
I'm just going to wait it out until a newer version of the package is released, I guess.

**Comment by Nicholas-Lewis-USDA** [comment] 2020-07-09 17:23
They are on 0.3.3 so if you are on 0.2.5 you have quite a old one.

https://pypi.org/project/scholarly/

Many changes have been made and many of them very helpful, I high suggest you update and review.

**Comment by chuntul** [comment] 2020-07-11 17:55
The issue I was having is the same as OP's - Google Scholar is probably blocking our IP.

Exact issue listed here: #139 
Threads to read to solve problem: #125 

Apparently, scholarly has a use_proxy method, but I don't know if it still works because it isn't documented. See [here](https://github.com/scholarly-python-package/scholarly/tree/fe574671e460bd4a57817804ad637c74d582d67d#using-proxies).

**Comment by SakuraX99** [comment] 2020-07-31 02:26
I have meet the same issue and I have tried the proxy method of free-proxy in README on a server in CMU:
def set_new_proxy():
    while True:
        proxy = FreeProxy(rand=True, timeout=1).get()
        proxy_works = scholarly.use_proxy(http=proxy, https=proxy)
        if proxy_works:
            break
    print("Working proxy:", proxy)
    return proxy

def get_articleInfo(title):
    while True:
        try:
            search_query = scholarly.search_pubs(title)
            print("Got the results of the query")
            break
        except Exception as e:
            print("Trying new proxy")
            set_new_proxy()

    pub = next(search_query)

    while True:
        try:
            break
        except Exception as e:
            print("Trying new proxy")
            set_new_proxy()
    return pub

If I try to catch the publication straightly,I got the "Cannot fetch the page from Google Scholar" exception. So I write as below:

source_data = open("iclr_year_conf_title_author_url_biburl_final_2017-2019.txt")
line = source_data.readline()
while line:
    nowTime = time.strftime("%Y-%m-%d %H:%M:%S")
    print("-------------------------------------------------")
    print(nowTime)
    line = source_data.readline()
    data_array = line.split(" ##### ")
    print(get_articleInfo(data_array[2]))//print the info
    print()

Unfortunately it terms out that this can rarely get the data from scholarly after lots of new IP tried:
-------------------------------------------------
2020-07-30 22:08:12
Trying new proxy
Working proxy: http://80.187.140.74:8080
Trying new proxy
Working proxy: http://118.27.18.60:8081
Trying new proxy
Working proxy: http://139.99.105.185:80
Trying new proxy
Working proxy: None
Trying new proxy
Working proxy: http://139.99.105.185:80
Trying new proxy
Working proxy: None
Trying new proxy
Working proxy: http://144.217.101.245:3129
......
Could anyone have some solution for this?

**Comment by silvavn** [comment] 2020-07-31 02:32
The only solution is to get new proxies or to wait for a day or two for a cooldown period (assuming that google has not banned you permanently). Another option is solve captchas manually using Selenium.

**Comment by dogan-mustafa** [comment] 2020-08-08 16:42
I have met the same issue while trying to get citations of a publication. 
The previous issue about citedby method listed in #128 
I tried the same code in issue #128 

```
from scholarly import scholarly

tor_sock_port = 9150
tor_control_port = 9151
scholarly.use_tor(tor_sock_port, tor_control_port, "")
search_query = scholarly.search_author('Steven A Cholewiak')
author = next(search_query).fill()
print(author)

# Take a closer look at the first publication
pub = author.publications[0].fill()
print(pub)

# Which papers cited that publication?
print([citation.bibtex['title'] for citation in pub.citedby])
```
However, I am still getting an Exception: Cannot fetch the page from Google Scholar.
I used the Scholarly version 0.4.0.1.

Furthermore, I strongly believe that the issue is caused by citedby method because I separately tried other functions such as search_author and search_pubs methods and they worked properly.

**Comment by ipeirotis** [comment] 2020-08-08 16:52
Just tried the code:

```python
search_query = scholarly.search_author('Steven A Cholewiak')
author = next(search_query).fill()
print(author)

# Take a closer look at the first publication
pub = author.publications[0].fill()
print(pub)

# Which papers cited that publication?
print([citation.bib['title'] for citation in pub.citedby])
```

and it works without an issue. Note that we use `citation.bib` and not `citation.bibtex`.

You may want to use a different proxy instead of tor, as it seems that all the exit nodes of Tor are getting overloaded and marked as bots. Or try a direct connection from a different machine.

Or perhaps use a paid service that provides proxy capabilities.

**Closed by ipeirotis** 2020-08-08 16:52 UTC

**Comment by chinmoybasak** [comment] 2022-06-29 07:14
```
    author = next(search_query).fill()
AttributeError: 'dict' object has no attribute 'fill'
```

Is anyone getting this error?? scholarly v 1.7.1
